/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.messages;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import test.backend.www.model.hotelbeds.basic.model.AuditData;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public abstract class AbstractGenericResponse {

	private String echoToken;
	@NotNull
	private AuditData auditData;
	private HotelbedsError error;
	private String lsection;


}