/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.messages;

import java.time.LocalDate;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import test.backend.www.model.hotelbeds.basic.common.SimpleTypes.BookingListFilterType;
import test.backend.www.model.hotelbeds.basic.convert.json.CustomDateDeserializer;
import test.backend.www.model.hotelbeds.basic.convert.json.CustomDateSerializer;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@EqualsAndHashCode(callSuper=false)
public class BookingListRQ extends AbstractGenericRequest {

	@JsonProperty
	@JsonSerialize(using = CustomDateSerializer.class) @JsonDeserialize(using = CustomDateDeserializer.class)
	@NotNull
	private LocalDate start;
	@JsonProperty
	@JsonSerialize(using = CustomDateSerializer.class) @JsonDeserialize(using = CustomDateDeserializer.class)
	@NotNull
	private LocalDate end;
	@NotNull
	private Integer from;
	@NotNull
	private Integer to;
	@NotNull
	private Boolean includeCancelled;
	@NotNull
	private BookingListFilterType filterType;


}