spring:
  application:
    name: SampleBackend
  datasource:
    initialize: false
server:
  context-path:
iata:
  base_url: http://iata.api.mashery.com/kronos/api
sabre:
  base_url: https://api.test.sabre.com
eventbrite:
  base_url: https://www.eventbriteapi.com/v3
hotelbeds:
  base_url: https://api.test.hotelbeds.com/hotel-api/0.2
sita:
  base_url: https://airport.api.aero