spring:
  application:
    name: SampleBackend
  datasource:
    initialize: false
server:
  context-path:
sabre:
  base_url: https://api.test.sabre.com
hotelbeds:
  base_url: https://api.test.hotelbeds.com/hotel-api/0.2