/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.model;

import java.math.BigDecimal;
import java.util.List;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import test.backend.www.model.hotelbeds.basic.common.SimpleTypes.RateType;
import test.backend.www.model.hotelbeds.basic.convert.json.RateSerializer;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class BasicRate {

	@JsonProperty
	private String rateKey;
	private String rateClass;
	@Valid
	private RateType rateType;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal net;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal discount;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal discountPCT;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal sellingRate;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal hotelSellingRate;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal amount;
	private String hotelCurrency;
	private Boolean hotelMandatory;
	private List<DailyRate> dailyRates;
	private Integer allotment;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal commission;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal commissionVAT;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal commissionPCT;


}