/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.model;

import java.math.BigDecimal;

import javax.validation.Valid;
import javax.validation.constraints.Min;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import test.backend.www.model.hotelbeds.basic.common.SimpleTypes.HotelPackage;
import test.backend.www.model.hotelbeds.basic.common.SimpleTypes.ShowDirectPayment;
import test.backend.www.model.hotelbeds.basic.convert.json.RateSerializer;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@AllArgsConstructor
public class Filter {

	@Min(value = 1)
	private Integer maxHotels;
	@Min(value = 1)
	private Integer maxRooms;
	@Min(value = 0)
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal minRate;
	@Min(value = 0)
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal maxRate;
	@Min(value = 1)
	private Integer maxRatesPerRoom;
	private Boolean packaging;
	@Valid
	private ShowDirectPayment paymentType;
	@Valid
	private HotelPackage hotelPackage;
	@Min(value = 1)
	private Integer minCategory;
	@Min(value = 1)
	private Integer maxCategory;


}