/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.model;

import java.math.BigDecimal;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import test.backend.www.model.hotelbeds.basic.annotation.validators.ValidGeoLocation;
import test.backend.www.model.hotelbeds.util.UnitMeasure;

@JsonInclude(Include.NON_NULL)
@ValidGeoLocation
@ToString
@NoArgsConstructor
@Data
public class GeoLocation
{

  @NotNull
  private BigDecimal longitude;
  @NotNull
  private BigDecimal latitude;
  private BigDecimal radius;
  private UnitMeasure unit;
  private BigDecimal secondaryLatitude;
  private BigDecimal secondaryLongitude;

}