/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.model;

import java.math.BigDecimal;
import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import test.backend.www.model.hotelbeds.basic.convert.json.CustomDateDeserializer;
import test.backend.www.model.hotelbeds.basic.convert.json.CustomDateSerializer;
import test.backend.www.model.hotelbeds.basic.convert.json.RateSerializer;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class RateSupplement {

	private String code;
	private String name;
	@JsonProperty
	@JsonSerialize(using = CustomDateSerializer.class) @JsonDeserialize(using = CustomDateDeserializer.class)
	private LocalDate from;
	@JsonProperty
	@JsonSerialize(using = CustomDateSerializer.class) @JsonDeserialize(using = CustomDateDeserializer.class)
	private LocalDate to;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal amount;
	private Integer nights;
	private Integer paxNumber;


}