/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.model;

import java.math.BigDecimal;
import java.util.List;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import test.backend.www.model.hotelbeds.basic.common.SimpleTypes.PaymentType;
import test.backend.www.model.hotelbeds.basic.convert.json.RateSerializer;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
@EqualsAndHashCode(callSuper=false)
public class Rate extends BasicRate {

	private String rateName;
	private String rateCommentsId;
	private String rateComments;
	private PaymentType paymentType;
	private Boolean packaging;
	private String boardCode;
	private String boardName;
	private List<CancellationPolicy> cancellationPolicies;
	private Taxes taxes;
	private RateBreakDown rateBreakDown;
	private Integer rooms;
	private Integer adults;
	private Integer children;
	private String childrenAges;
	private List<Promotion> promotions;
	private List<Offer> offers;
	@Valid
	private List<ShiftRate> shiftRates;
	@JsonSerialize(using = RateSerializer.class)
	private BigDecimal rateup;


}