/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.model;

import java.util.List;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import test.backend.www.model.hotelbeds.basic.common.SimpleTypes.BookingStatus;

@JsonInclude(Include.NON_NULL)
@ToString
@NoArgsConstructor
@Data
public class Room {

	private BookingStatus status;
	private String code;
	private String name;
	private List<Pax> paxes;
	@Valid
	private List<Rate> rates;


}