/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.annotation.validators;


import java.time.LocalDate;

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;


public class FutureForLocalDateValidator implements ConstraintValidator<FutureForLocalDate, LocalDate> {

    @Override
    public void initialize(FutureForLocalDate constraintAnnotation) {
        //
    }

    @Override
    public boolean isValid(LocalDate date, ConstraintValidatorContext context) {
        if (date == null) {
            return true;
        }
        if (date.isEqual(LocalDate.now())) {
            return true;
        }
        return date.isAfter(LocalDate.now());
    }

}
