/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.annotation.validators;

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

import test.backend.www.model.hotelbeds.basic.model.GeoLocation;

public class ValidGeoLocationValidator implements ConstraintValidator<ValidGeoLocation, GeoLocation>
{

  @Override
  public void initialize(ValidGeoLocation constraintAnnotation)
  {
    // TODO Auto-generated method stub
  }

  @Override
  public boolean isValid(GeoLocation geoLocation, ConstraintValidatorContext context)
  {
    if (geoLocation.getRadius() != null && geoLocation.getUnit() != null && geoLocation.getSecondaryLongitude() == null
        && geoLocation.getSecondaryLatitude() == null)
    {
      return true;
    }
    else if (geoLocation.getSecondaryLongitude() != null && geoLocation.getSecondaryLatitude() != null && geoLocation.getRadius() == null
        && geoLocation.getUnit() == null)
    {
      return true;
    }
    return false;
  }

}
