/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.annotation.validators;

import java.util.List;

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

import test.backend.www.model.hotelbeds.basic.model.ReviewFilter;

public class ValidReviewFilterValidator implements ConstraintValidator<ValidReviewFilter, List<ReviewFilter>> {


    @Override
    public void initialize(ValidReviewFilter constraintAnnotation) {
        // TODO Auto-generated method stub
    }

    @Override
    public boolean isValid(List<ReviewFilter> value, ConstraintValidatorContext context) {
        context.disableDefaultConstraintViolation();
        boolean result = true;
        if (value != null) {
            for (ReviewFilter review : value) {
                if (review.getMaxRate() == null && review.getMinRate() == null) {
                    context.buildConstraintViolationWithTemplate(
                        "{com.hotelbeds.distribution.hotel_api_webapp.webapp.api.model.ReviewFilter.rates.null.message}").addConstraintViolation();
                    result = false;
                } else if (result && review.getMaxRate() != null && review.getMinRate() != null
                    && (review.getMaxRate().compareTo(review.getMinRate()) < 0)) {
                    context.buildConstraintViolationWithTemplate(
                        "{com.hotelbeds.distribution.hotel_api_webapp.webapp.api.model.ReviewFilter.rates.value.message}").addConstraintViolation();
                    result = false;
                }
                if (review.getMinReviewCount() != null && review.getMinReviewCount() == 0) {
                    context.buildConstraintViolationWithTemplate(
                        "{com.hotelbeds.distribution.hotel_api_webapp.webapp.api.model.ReviewFilter.reviewCounts.zero.message}")
                        .addConstraintViolation();
                    result = false;
                }
            }
        }
        return result;
    }

}
