/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.annotation.validators;

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

import test.backend.www.model.hotelbeds.basic.common.SimpleTypes;
import test.backend.www.model.hotelbeds.basic.model.Filter;

public class ValidLimitFilterValidator implements ConstraintValidator<ValidLimitFilter, Filter> {

    @Override
    public void initialize(final ValidLimitFilter constraintAnnotation) {
        // TODO Auto-generated method stub
    }

    @Override
    public boolean isValid(final Filter limit, final ConstraintValidatorContext context) {
        if (limit != null) {
            if (limit.getMinRate() != null && limit.getMaxRate() != null && limit.getMinRate().compareTo(limit.getMaxRate()) > 0) {
                context.buildConstraintViolationWithTemplate(SimpleTypes.WRONG_LIMITS_PRICE_RANGE_MESSAGE).addConstraintViolation();
                return false;

            }
            if (limit.getMinCategory() != null && limit.getMaxCategory() != null) {
                if (limit.getMinCategory() > limit.getMaxCategory()) {
                    context.disableDefaultConstraintViolation();
                    context.buildConstraintViolationWithTemplate(SimpleTypes.WRONG_LIMITS_CATEGORY_RANGE_MESSAGE).addConstraintViolation();
                    return false;
                }
            }
        }
        return true;
    }
}
