/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.util;

import java.util.StringJoiner;


public class ObjectJoiner {

    public static String join(CharSequence separator, Object... arguments) {
        StringJoiner st = new StringJoiner(separator);
        if (arguments != null) {
            for (Object object : arguments) {
                if (object != null) {
                    st.add(object.toString());
                } else {
                    st.add("");
                }
            }
        }
        return st.toString();
    }

    public static String simplyJoin(Object... arguments) {
        return join("", arguments);
    }
}
