/**
 * Autogenerated code by SdkModelGenerator.
 * Do not edit. Any modification on this file will be removed automatically after project build
 *
 */
package test.backend.www.model.hotelbeds.basic.util;

import java.util.ArrayList;
import java.util.List;


public class Utils {

    public static List<String> splitToList(Iterable<String> split) {
        List<String> parts = new ArrayList<String>();
        for (String string : split) {
            parts.add(string);
        }
        return parts;
    }
}
